import { FeedState } from '../types/socialTypes';

export const mockFeedState: FeedState = {
  currentUserId: 'user1',
  users: {
    user1: {
      id: 'user1',
      name: 'Alex Johnson',
      avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
      headline: 'Computer Science Student',
      type: 'student',
      connections: ['user2', 'user3'],
      pendingConnections: ['user4'],
      joinedClubs: [
        { clubId: 'club1', role: 'member' },
        { clubId: 'club2', role: 'admin' },
      ],
      skills: ['React Native', 'Python', 'Machine Learning'],
      department: 'Computer Science',
      email: 'alex.j@university.edu',
    },
    user2: {
      id: 'user2',
      name: 'Sarah Chen',
      avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
      headline: 'Professor of Engineering',
      type: 'faculty',
      connections: ['user1'],
      pendingConnections: [],
      joinedClubs: [
        { clubId: 'club1', role: 'admin' },
        { clubId: 'club3', role: 'moderator' },
      ],
      department: 'Electrical Engineering',
      email: 'schen@university.edu',
    },
    user3: {
      id: 'user3',
      name: 'David Lee',
      avatarUrl: 'https://randomuser.me/api/portraits/men/65.jpg',
      headline: 'Electrical Engineering Senior',
      type: 'student',
      connections: ['user1'],
      pendingConnections: [],
      joinedClubs: [
        { clubId: 'club1', role: 'member' },
        { clubId: 'club4', role: 'member' },
      ],
    },
    user4: {
      id: 'user4',
      name: 'Maya Rodriguez',
      avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
      headline: 'Alumni - Software Engineer',
      type: 'alumni',
      connections: [],
      pendingConnections: ['user1'],
      joinedClubs: [{ clubId: 'club2', role: 'member' }],
    },
  },
  clubs: {
    club1: {
      id: 'club1',
      name: 'Robotics Club',
      logoUrl: 'https://img.icons8.com/color/96/robot-2.png',
      bannerUrl: 'https://images.unsplash.com/photo-1581091226033-d5c48150dbaa',
      description: 'Building innovative robots since 2015. Join us for workshops and competitions!',
      adminIds: ['user2'],
      memberCount: 120,
      upcomingEvent: 'Robotics Workshop - Dec 20 @ Engineering Building',
      tags: ['Engineering', 'Competitions', 'Hardware'],
      createdAt: new Date('2020-09-01'),
      socialLinks: {
        website: 'robotics-uni.edu',
        discord: 'discord.gg/robotics',
      },
    },
    club2: {
      id: 'club2',
      name: 'Debate Society',
      bannerUrl: 'https://images.unsplash.com/photo-1581091226033-d5c48150dbaa',
      logoUrl: 'https://img.icons8.com/color/96/microphone.png',
      description: 'Sharpen your critical thinking and public speaking skills',
      adminIds: ['user1'],
      memberCount: 85,
      upcomingEvent: 'Annual Inter-University Debate Championship',
      tags: ['Public Speaking', 'Critical Thinking'],
      createdAt: new Date('2019-03-15'),
      socialLinks: {
        instagram: '@unidebate',
      },
    },
    club3: {
      id: 'club3',
      name: 'AI Research Group',
      bannerUrl: 'https://images.unsplash.com/photo-1581091226033-d5c48150dbaa',
      logoUrl: 'https://img.icons8.com/color/96/artificial-intelligence.png',
      description: 'Exploring cutting-edge AI technologies and applications',
      adminIds: ['user2'],
      memberCount: 45,
      tags: ['Machine Learning', 'Research'],
      createdAt: new Date('2021-01-20'),
    },
  },
  posts: [
    {
      id: 'post1',
      authorId: 'user1',
      content: 'Just completed my final robotics project! Check out the autonomous navigation system.',
      type: 'image',
      mediaUrls: ['https://images.unsplash.com/photo-1603791440384-56cd371ee9a7'],
      createdAt: new Date('2023-12-15T10:30:00Z'),
      likes: ['user2', 'user3'],
      comments: [
        {
          id: 'comment1',
          userId: 'user2',
          text: 'Impressive work, Alex! The sensor integration looks flawless.',
          createdAt: new Date('2023-12-15T11:00:00Z'),
          likes: ['user3'],
        },
      ],
      shares: 5,
    },
    {
      id: 'post2',
      authorId: 'user2',
      content: 'Join our robotics workshop this Friday! Learn to build autonomous drones from scratch.',
      type: 'event',
      clubId: 'club1',
      eventDetails: {
        date: new Date('2023-12-20T14:00:00Z'),
        location: 'Engineering Building Room 205',
      },
      createdAt: new Date('2023-12-14T09:15:00Z'),
      likes: ['user1', 'user3'],
      comments: [],
      shares: 12,
      isPinned: true,
    },
    {
      id: 'post3',
      authorId: 'club1',
      content: 'Congratulations to our team for winning the regional robotics competition! 🏆',
      type: 'image',
      mediaUrls: ['https://images.unsplash.com/photo-1581091226033-d5c48150dbaa'],
      clubId: 'club1',
      createdAt: new Date('2023-12-13T08:45:00Z'),
      likes: ['user1', 'user2', 'user3'],
      comments: [
        {
          id: 'comment2',
          userId: 'user1',
          text: 'So proud of our team! Hard work pays off.',
          createdAt: new Date('2023-12-13T09:00:00Z'),
          likes: ['user3'],
        },
      ],
      shares: 3,
    },
    {
      id: 'post4',
      authorId: 'user1',
      content: 'This month\'s debate topic: "AI in Education – Boon or Bane?" Join the discussion!',
      type: 'poll',
      clubId: 'club2',
      pollOptions: [
        {
          id: 'opt1',
          text: 'Boon - Enhances learning',
          votes: 24,
          voters: ['user1', 'user3'],
        },
        {
          id: 'opt2',
          text: 'Bane - Reduces human interaction',
          votes: 8,
          voters: ['user4'],
        },
      ],
      createdAt: new Date('2023-12-12T07:30:00Z'),
      likes: ['user1', 'user2'],
      comments: [],
      shares: 4,
    },
  ],
};